language: python
python:
  - "3.8-dev"
install: pip install -r requirements-dev.txt codecov
script:
  - pycodestyle .
  - flake8 .
  - coverage run -a --source=cloudinary_storage manage.py test -v 2
after_success:
  - codecov
